# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # To upgrade hooks run: `prek autoupdate`
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=750']
        exclude: ^uv.lock$
      - id: check-toml
      - id: check-yaml
        args:
        - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos.git
    rev: v1.49.0
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: local-ruff-check
        name: ruff check
        entry: pdm run ruff check --force-exclude --fix --exit-non-zero-on-fix
        require_serial: true
        language: unsupported
        types: [python]

      - id: local-ruff-format
        name: ruff format
        entry: pdm run ruff format --force-exclude --exit-non-zero-on-format
        require_serial: true
        language: unsupported
        types: [python]

      - id: fast-lint
        name: check type hints by ty
        entry: pdm run ty check
        language: system
        pass_filenames: false
