upstream dcagent_api {
    server 127.0.0.1:9313;
}

server {
    root /var/www/html;
    index index.html;
    
    server_name _;

    location /api {
        proxy_pass http://dcagent_api;
    }

    location /admin {
        alias /var/www/html/dist;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
