[group:DCAgent]
programs=api,embedding,reranker,worker

[program:api]
command=uv run --no-config --no-cache --no-sync gunicorn -c ./deployment/gunicorn_config.py app.main:app
directory=/home/ubuntu/github/%(group_name)s/backend
stdout=/home/ubuntu/github/%(group_name)s/backend/logs/%(program_name)s.log
user=ubuntu
numprocs=1
redirect_stderr=true

[program:embedding]
command=uv run --no-config --no-cache --no-sync gunicorn -c ./deployment/%(program_name)s.py "app."%(program_name)s"_service:create_production_app()"
directory=/home/ubuntu/github/%(group_name)s/backend
stdout=/home/ubuntu/github/%(group_name)s/backend/logs/%(program_name)s.log
user=ubuntu
numprocs=1
redirect_stderr=true

[program:reranker]
command=uv run --no-config --no-cache --no-sync gunicorn -c ./deployment/%(program_name)s.py "app."%(program_name)s"_service:create_production_app()"
directory=/home/ubuntu/github/%(group_name)s/backend
stdout=/home/ubuntu/github/%(group_name)s/backend/logs/%(program_name)s.log
user=ubuntu
numprocs=1
redirect_stderr=true

[program:worker]
command=uv run --no-config --no-cache --no-sync python -m app.structured_worker
directory=/home/ubuntu/github/%(group_name)s/backend
stdout=/home/ubuntu/github/%(group_name)s/backend/logs/%(program_name)s.log
user=ubuntu
numprocs=1
redirect_stderr=true
